Update generate.yml

diff --git a/.github/workflows/generate.yml b/.github/workflows/generate.yml
--- a/.github/workflows/generate.yml
+++ b/.github/workflows/generate.yml
@@ -163,6 +163,7 @@ jobs:
         run: |
           git status
           cd clients/ts;
+          if [ ! -f .npmrc ]; then echo "missing .npmrc" && exit 1; fi
           npm install
           npm run build
           npm publish --access public
@@ -173,6 +174,7 @@ jobs:
         run: |
           git status
           cd clients/ts;
+          if [ ! -f .npmrc ]; then echo "missing .npmrc" && exit 1; fi
           npm install
           npm run build
           npm publish --access public --tag beta
